//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public int id { get; set; }
        [Required]
        [StringLength(12)]
        [Display(Name = "First Name")]
        public string First_Name { get; set; }
        [Required]
        [StringLength(12)]
        [Display(Name = "Last Name")]
        public string Last_name { get; set; }
        [EmailAddress]
        [Required]
        public string E_mail { get; set; }
        [RegularExpression(@"^(0)?(77|78|79)\d{7}$")]
        public Nullable<int> Phone { get; set; }
        [Range(18,85)]
        public Nullable<int> Age { get; set; }
        [StringLength(10)]
        public string Job_title { get; set; }
        [DisplayFormat(NullDisplayText = "", ConvertEmptyStringToNull = true, DataFormatString = "{0:Male;Female}")]


        public Nullable<bool> Gender { get; set; }
    }
}
